In [4]:
import os

print("DETECTRON2_DATASETS:", os.environ.get("DETECTRON2_DATASETS"))

DETECTRON2_DATASETS: None


In [5]:
import torch
init_scores = torch.rand((1024, 60), dtype=torch.float32, device="cuda")
topk_class_indices = torch.topk(init_scores, 10, dim=1)

In [6]:
topk_class_indices.indices

tensor([[ 0,  3, 50,  ..., 37, 10,  1],
        [14, 27, 47,  ..., 30, 29, 11],
        [37, 54, 59,  ..., 16, 39, 21],
        ...,
        [40, 36,  2,  ..., 19, 22, 30],
        [ 5,  7, 36,  ..., 39, 21, 42],
        [43, 26, 36,  ..., 16, 44,  1]], device='cuda:0')

In [7]:
class_indices = torch.randint(0, 80,(1024, 10))

In [8]:
torch.sort(class_indices, dim=1).values

tensor([[ 5, 13, 25,  ..., 61, 63, 70],
        [28, 29, 44,  ..., 62, 66, 78],
        [ 3,  6,  8,  ..., 65, 74, 78],
        ...,
        [ 0,  6,  6,  ..., 55, 58, 74],
        [10, 23, 39,  ..., 63, 69, 72],
        [ 0,  6, 13,  ..., 54, 63, 68]])

In [9]:
indexes = torch.tensor([0,1, 2, 3, 4])[None, None, :]

In [10]:
indexes.shape

torch.Size([1, 1, 5])

In [11]:
indexes

tensor([[[0, 1, 2, 3, 4]]])

In [12]:
indexes = indexes.repeat(2,2,1)

In [13]:
indexes, indexes.shape

(tensor([[[0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4]],
 
         [[0, 1, 2, 3, 4],
          [0, 1, 2, 3, 4]]]),
 torch.Size([2, 2, 5]))

In [14]:
class_indices = torch.tensor([3, 5]).view(2, 1, 1)

In [15]:
class_indices

tensor([[[3]],

        [[5]]])

In [16]:
indexes != class_indices

tensor([[[ True,  True,  True, False,  True],
         [ True,  True,  True, False,  True]],

        [[ True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True]]])

In [19]:
feat = torch.rand((1024, 49, 60))
class_indices = torch.randint(0, 60, (1024, 10))
class_indices.shape
spatial_size = 49

In [ ]:
intra_feats = torch.gather(feat, 2, class_indices[:, None, :].repeat(1, spatial_size, 1))